DECLARE @CodEntidad int
SET @CodEntidad = 987, 951, 969 

DELETE FROM dfxENTFILTROSUSER WHERE CodEntidad = @CodEntidad
DELETE FROM dfxENTFILTROS WHERE CodEntidad = @CodEntidad
DELETE FROM dfxENTCOLUMNASUSER WHERE CodEntidad = @CodEntidad
DELETE FROM dfxENTCORTESUSER WHERE CodEntidad = @CodEntidad
DELETE FROM dfxENTCONFIGURACIONUSER WHERE CodEntidad = @CodEntidad
DELETE FROM dfxENTCOLUMNAS WHERE CodEntidad = @CodEntidad
DELETE FROM dfxENTESTRUCTURAS WHERE CodEntidad = @CodEntidad
--DELETE FROM appENTTPACCION WHERE CodEntidad = @CodEntidad

DELETE FROM dfxENTFILTROSSETUSER WHERE CodEntidad = @CodEntidad
--DELETE FROM appENTTPACCION WHERE CodEntidad = @CodEntidad
--DELETE FROM appENTIDADES WHERE CodEntidad = @CodEntidad
DELETE FROM appENTIDADESUSERFAV WHERE CodEntidad = @CodEntidad
