-- ESTAS LINEAS AMPLIAN EL CAMPO Texto

IF EXISTS(SELECT * FROM sys.columns WHERE name='Texto' and object_id = OBJECT_ID('DOCUMENTACIONESWEB'))
BEGIN
	ALTER TABLE DOCUMENTACIONESWEB
	ALTER COLUMN Texto Memo NULL
END

-- ELIMINAN TODO LO QUE TIENE LA TABLA DOCUMENTACIONWEB para TYC
DELETE FROM DOCUMENTACIONESWEB
WHERE CodTpDocumentacionWEB = 'TYC'



INSERT INTO AUDITORIASREF(NomEntidad)
VALUES('DOCWEB')

DECLARE @CodAuditoria numeric
SELECT @CodAuditoria = SCOPE_IDENTITY()

INSERT INTO DOCUMENTACIONESWEB (CodTpDocumentacionWEB, Descripcion, CodFondo, FechaVigencia, EstaAnulado, Texto, CodAuditoriaRef)
	SELECT 'TYC' As CodTpDocumentacionWEB, --Términos y Condiciones
		   CONVERT(VARCHAR(80), TERMINOSCONDFDO.TerminosCondiciones),
		   TERMINOSCONDFDO.CodFondo,
		   TERMINOSCONDFDO.FechaInicioVigencia,
		   TERMINOSCONDFDO.EstaAnulado,
		   TERMINOSCONDFDO.TerminosCondiciones, 
		   @CodAuditoria	FROM TERMINOSCONDFDO
	WHERE NOT EXISTS (SELECT 1
					  FROM DOCUMENTACIONESWEB
					  WHERE DOCUMENTACIONESWEB.CodTpDocumentacionWEB = 'TYC'
					  AND DOCUMENTACIONESWEB.CodFondo = TERMINOSCONDFDO.CodFondo
					  AND DOCUMENTACIONESWEB.FechaVigencia = TERMINOSCONDFDO.FechaInicioVigencia)

SELECT * FROM DOCUMENTACIONESWEB
WHERE CodTpDocumentacionWEB = 'TYC'