
SELECT PERSONAS.Nombre, PERSONAS.Apellido,  TPDOCIDENTIDAD.Descripcion as TipoDocumento, PERSONAS.NumDocumento,PERSONAS.CUIL,PERSONAS.CUIT,
CUOTAPARTISTAS.NumCuotapartista,PERSONAS.CodInterfazBanco as IDCobis,
SUCURSALES.NumSucursal as NumSucursalCpt,SUCURSALES.Descripcion, SUM(LIQUIDACIONES.CantCuotapartes) As Saldo,
CPTCTASBANCARIAS.NumeroCuenta, CPTCTASBANCARIAS.NumSucursal as NumSucursalCtaBancaria,
CPTCTASBANCARIAS.EstaAnulado CtaBancAnulada
FROM LIQUIDACIONES
INNER JOIN CUOTAPARTISTAS ON LIQUIDACIONES.CodCuotapartista = CUOTAPARTISTAS.CodCuotapartista
	LEFT JOIN CPTCTASBANCARIAS ON CUOTAPARTISTAS.CodCuotapartista=CPTCTASBANCARIAS.CodCuotapartista
	INNER JOIN SUCURSALES ON SUCURSALES.CodSucursal=CUOTAPARTISTAS.CodSucursal
	INNER JOIN CONDOMINIOS ON CUOTAPARTISTAS.CodCuotapartista=CONDOMINIOS.CodCuotapartista
	INNER JOIN PERSONAS ON PERSONAS.CodPersona=CONDOMINIOS.CodPersona
	LEFT JOIN TPDOCIDENTIDAD ON PERSONAS.CodTpDocIdentidad=TPDOCIDENTIDAD.CodTpDocIdentidad
WHERE PERSONAS.CodSistemaExtOrig='CB' AND CUOTAPARTISTAS.CodSistemaExtOrig='CB' AND PERSONAS.CodInterfazBanco IS NOT NULL
GROUP BY PERSONAS.Nombre, PERSONAS.Apellido,  TPDOCIDENTIDAD.Descripcion, PERSONAS.NumDocumento,PERSONAS.CUIL,PERSONAS.CUIT,
CUOTAPARTISTAS.NumCuotapartista,PERSONAS.CodInterfazBanco,SUCURSALES.NumSucursal,SUCURSALES.Descripcion,
CPTCTASBANCARIAS.NumeroCuenta, CPTCTASBANCARIAS.NumSucursal ,
CPTCTASBANCARIAS.EstaAnulado,
LIQUIDACIONES.CodFondo,LIQUIDACIONES.CodCondicionIngEgr, LIQUIDACIONES.CodTpValorCp, LIQUIDACIONES.CodCuotapartista, LIQUIDACIONES.CodMoneda
HAVING SUM(LIQUIDACIONES.CantCuotapartes) > 0
ORDER BY NumCuotapartista
