
SELECT FONDOSREAL.Nombre + ' ' + TPVALORESCP.Abreviatura as Fondo, TPVALORESCP.CodCAFCI, SuscripcionMinima, RescateMinimo, CONVERT(int,ValorNumero) as Plazo, AplicaPersonaFisica, AplicaPersonaJuridica
FROM CONDICIONESINGEGR
INNER JOIN FONDOSREAL ON CONDICIONESINGEGR.CodFondo=FONDOSREAL.CodFondo
INNER JOIN TPVALORESCP ON TPVALORESCP.CodFondo=FONDOSREAL.CodFondo
INNER JOIN FONDOSPARAM ON FONDOSPARAM.CodFondo=FONDOSREAL.CodFondo AND CodParametroFdo='PLARES'
WHERE CONDICIONESINGEGR.CodInterfaz='ACSA'

