IF EXISTS (SELECT * FROM syscolumns WHERE name = 'Precio' and id = OBJECT_ID('OPERBURSATILESIT'))
BEGIN
	ALTER TABLE OPERBURSATILESIT ALTER COLUMN Precio Precio NULL; 
END
GO
IF EXISTS (SELECT * FROM syscolumns WHERE name = 'PrecioCarga' and id = OBJECT_ID('OPERBURSATILESIT'))
BEGIN
	ALTER TABLE OPERBURSATILESIT ALTER COLUMN PrecioCarga Precio NULL; 
END
GO
