/*
Nombre: spCUOTAPARTISTAS_Update
Funci�n: Stored procedure de actualizaci�n de datos.
Fecha Generacion: 30/oct./2017
Autor: Stored procedure generado automaticamente. No modificar ni agregar contenido ya que el mismo puede ser sobreescrito.
Template: Update Version 1.1
*/ 
exec sp_CreateProcedure 'dbo.spCUOTAPARTISTAS_Update'
GO

ALTER PROCEDURE dbo.spCUOTAPARTISTAS_Update
    @CodCuotapartista CodigoLargo OUTPUT,
    @CodCategoria CodigoMedio OUTPUT,
    @CodAgColocador CodigoMedio OUTPUT,
    @CodSucursal CodigoMedio OUTPUT,
    @CodAgColocadorOfCta CodigoMedio OUTPUT,
    @CodSucursalOfCta CodigoMedio OUTPUT,
    @CodOficialCta CodigoMedio OUTPUT,
    @CodSegmentoInv CodigoMedio OUTPUT,
    @CodCanalVta CodigoMedio OUTPUT,
    @CodProvincia CodigoMedio OUTPUT,
    @CodPais CodigoMedio OUTPUT,
    @Nombre Nombre OUTPUT,
    @FechaIngreso Fecha OUTPUT,
    @Perfil NumeroMedio OUTPUT,
    @Calle Calle OUTPUT,
    @AlturaCalle AlturaCalle OUTPUT,
    @Piso Piso OUTPUT,
    @Departamento Departamento OUTPUT,
    @CodigoPostal CodigoPostal OUTPUT,
    @Localidad Localidad OUTPUT,
    @Telefono Telefono OUTPUT,
    @Fax Telefono OUTPUT,
    @EMail EMail OUTPUT,
    @NumCustodia DescripcionCorta OUTPUT,
    @NumCuotapartista NumeroLargo OUTPUT,
    @EsPersonaFisica Boolean OUTPUT,
    @RequiereFirmaConjunta Boolean OUTPUT,
    @NivelSeguridad Digito OUTPUT,
    @FechaInterfEntr Fecha OUTPUT,
    @CodInterfaz CodigoInterfaz OUTPUT,
    @CodReferente CodigoMedio OUTPUT,
    @NumAseguradora CodigoTextoLargo OUTPUT,
    @Observaciones Texto OUTPUT,
    @EstaAceptado Boolean OUTPUT,
    @ImpResumenCta Boolean OUTPUT,
    @CodCentroFisico CodigoMedio OUTPUT,
    @CodAreaPertenencia CodigoMedio OUTPUT,
    @ActividadPrincipal DescripcionMedia OUTPUT,
    @CodSectorInv CodigoMedio OUTPUT,
    @PoseeInstrPagoPerm Boolean OUTPUT,
    @CodInterfazAdicional CodigoInterfazLargo OUTPUT,
    @SincronizaCOBIS Boolean OUTPUT,
    @CodTpPerfilRiesgoCpt CodigoTextoMedio OUTPUT,
    @CodSistemaExtOrig CodigoTextoCorto OUTPUT,
    @CodInterfazBanco CodigoInterfazLargo OUTPUT,
    @CodActividad CodigoMedio OUTPUT,
    @CodTpInversor CodigoLargo OUTPUT,
    @CodTpCuotapartista CodigoLargo OUTPUT,
    @CodTpTitularidad CodigoCorto OUTPUT,
    @CodTpRecepEstCta CodigoTextoMedio OUTPUT,
    @Lote DescripcionMedia OUTPUT,
    @Manzana DescripcionCorta OUTPUT,
    @Urbanizacion DescripcionCorta OUTPUT,
    @Residencia DescripcionCorta OUTPUT,
    @UnidadVecinal DescripcionCorta OUTPUT,
    @RecibeTelefonicamente Boolean OUTPUT,
    @RecibeEMail Boolean OUTPUT,
    @NIFTIN AbreviaturaMedia OUTPUT,
    @TipoNIF AbreviaturaMedia OUTPUT

WITH ENCRYPTION

AS

    UPDATE CUOTAPARTISTAS SET
    CodCategoria=@CodCategoria,
    CodAgColocador=@CodAgColocador,
    CodSucursal=@CodSucursal,
    CodAgColocadorOfCta=@CodAgColocadorOfCta,
    CodSucursalOfCta=@CodSucursalOfCta,
    --CodOficialCta=@CodOficialCta,
    CodSegmentoInv=@CodSegmentoInv,
    CodCanalVta=@CodCanalVta,
    CodProvincia=@CodProvincia,
    CodPais=@CodPais,
    Nombre=@Nombre,
    FechaIngreso=@FechaIngreso,
    Perfil=@Perfil,
    Calle=@Calle,
    AlturaCalle=@AlturaCalle,
    Piso=@Piso,
    Departamento=@Departamento,
    CodigoPostal=@CodigoPostal,
    Localidad=@Localidad,
    Telefono=@Telefono,
    Fax=@Fax,
    EMail=@EMail,
    NumCustodia=@NumCustodia,
    NumCuotapartista=@NumCuotapartista,
    EsPersonaFisica=@EsPersonaFisica,
    RequiereFirmaConjunta=@RequiereFirmaConjunta,
    NivelSeguridad=@NivelSeguridad,
    FechaInterfEntr=@FechaInterfEntr,
    CodInterfaz=@CodInterfaz,
    CodReferente=@CodReferente,
    NumAseguradora=@NumAseguradora,
    Observaciones=@Observaciones,
    EstaAceptado=@EstaAceptado,
    ImpResumenCta=@ImpResumenCta,
    CodCentroFisico=@CodCentroFisico,
    CodAreaPertenencia=@CodAreaPertenencia,
    ActividadPrincipal=@ActividadPrincipal,
    CodSectorInv=@CodSectorInv,
    PoseeInstrPagoPerm=@PoseeInstrPagoPerm,
    CodInterfazAdicional=@CodInterfazAdicional,
    SincronizaCOBIS=@SincronizaCOBIS,
    CodTpPerfilRiesgoCpt=@CodTpPerfilRiesgoCpt,
    CodSistemaExtOrig=@CodSistemaExtOrig,
    CodInterfazBanco=@CodInterfazBanco,
    CodActividad=@CodActividad,
    CodTpInversor=@CodTpInversor,
    CodTpCuotapartista=@CodTpCuotapartista,
    CodTpTitularidad=@CodTpTitularidad,
    CodTpRecepEstCta=@CodTpRecepEstCta,
    Lote=@Lote,
    Manzana=@Manzana,
    Urbanizacion=@Urbanizacion,
    Residencia=@Residencia,
    UnidadVecinal=@UnidadVecinal,
    RecibeTelefonicamente=@RecibeTelefonicamente,
    RecibeEMail=@RecibeEMail,
    NIFTIN=@NIFTIN,
    TipoNIF=@TipoNIF

    WHERE
    CodCuotapartista=@CodCuotapartista

    RETURN @@ROWCOUNT
GO
