

	SELECT 
		SOLRESC.CodSolResc CodSolResc,
		LIQUIDACIONES.CodLiquidacion CodLiquidacion,
		FONDOSPARAM.CodParametroFdo CodParametroFdo,
		SOLRESCIMPMON.ValorCuotaparte ValorCuotaparte,
		SOLRESCIMPMON.CantCuotapartes CantCuotapartes,
		SOLRESCIMPMON.Importe Importe,
		SOLRESCIMPMON.CodAgColocador CodAgColocador,
		SOLRESCIMPMON.CodSucursal CodSucursal,
		SOLRESCIMPMON.serviceProc serviceProc,
		ISNULL(SOLRESCIMPMON.ImporteDif,0) ImporteDif,
		LIQUIDACIONES.Importe ImporteLiq,
		(SELECT TOP 1 ValorCuotaparte FROM VALORESCP where CodFondo = SOLRESC.CodFondo and CodTpValorCp = SOLRESC.CodTpValorCp and Fecha <= '20201103' ORDER BY Fecha DESC) AS UltValorCuotaparte,
		SOLRESCIMPMON.CodTpEstadoImpMon CodTpEstadoImpMon,

		--DATOS IMPACTO
		CUOTAPARTISTAS.NumCuotapartista AS NumCuotapartista,
		CUOTAPARTISTAS.Nombre AS Nombre,
		FONDOSREAL.NumFondo AS NumFondo,
		FONDOSREAL.CodFondo AS CodFondo,
		TPVALORESCP.Abreviatura as Abreviatura,
		'0101' [CentroCostoSucursal], --CPTCTASBANCARIAS.NumSucursal AS CentroCostoSucursal,

		--ORIGEN - DEBITO - FONDO
		'0101' [CuentaBancariaSucursal],
		TPCTAFDO.CodInterfaz as CuentaBancariaTipo,
		CTASBANCARIAS.NumeroCuenta as CuentaBancariaNumero,
		MONEDAS.CodInterfaz AS CuentaBancariaMoneda,

		--DESTINO - CREDITO - CPT
		'0' + LTRIM(CPTCTASBANCARIAS.NumSucursal) AS CuentaFondoSucursal ,
		TPCTABANCARIA.CodInterfaz AS CuentaFondoTipo ,
		CPTCTASBANCARIAS.NumeroCuenta AS CuentaFondoNumero ,
		MONEDAS.CodInterfaz AS CuentaFondoMoneda,

		CASE WHEN PERSONAS.CUIL IS NULL AND PERSONAS.CUIT IS NULL THEN
				(SELECT TOP 1 CodInterfaz FROM TPDOCIDENTIDAD WHERE CodDocIdentidad = 'DNI')
			WHEN PERSONAS.CUIL IS NULL THEN
				(SELECT TOP 1 CodInterfaz FROM TPDOCIDENTIDAD WHERE CodDocIdentidad = 'CUIT')
			ELSE
				(SELECT TOP 1 CodInterfaz FROM TPDOCIDENTIDAD WHERE CodDocIdentidad = 'CUIL')
			END TpDocumento,
		CASE WHEN PERSONAS.CUIL IS NULL AND PERSONAS.CUIT IS NULL THEN
				PERSONAS.NumDocumento
			WHEN PERSONAS.CUIL IS NOT NULL THEN
				PERSONAS.CUIL
			ELSE
				PERSONAS.CUIT
			END NumDocumento
	FROM SOLRESC
		INNER JOIN LIQUIDACIONES ON LIQUIDACIONES.CodSolResc = SOLRESC.CodSolResc AND LIQUIDACIONES.EstaAnulado = 0
		INNER JOIN FONDOSPARAM ON FONDOSPARAM.CodFondo = SOLRESC.CodFondo AND CodParametroFdo = 'IMSOT0'
		INNER JOIN SOLRESCIMPMON ON SOLRESCIMPMON.CodFondo = SOLRESC.CodFondo AND SOLRESCIMPMON.CodSolResc = SOLRESC.CodSolResc --AND SOLRESCIMPMON.CodTpEstadoImpMon = 'IR'
		INNER JOIN CUOTAPARTISTAS ON SOLRESC.CodCuotapartista = CUOTAPARTISTAS.CodCuotapartista
		INNER JOIN FONDOSREAL ON FONDOSREAL.CodFondo = SOLRESC.CodFondo
		INNER JOIN TPVALORESCP ON TPVALORESCP.CodFondo = SOLRESC.CodFondo AND TPVALORESCP.CodTpValorCp = SOLRESC.CodTpValorCp
		INNER JOIN AFECTACIONESCTABANC ON AFECTACIONESCTABANC.CodFondo = SOLRESC.CodFondo AND AFECTACIONESCTABANC.CodMoneda = SOLRESC.CodMoneda AND CodTpAfectacionBanc = 'LIQRES'
		INNER JOIN CTASBANCARIAS ON CTASBANCARIAS.CodCtaBancaria = AFECTACIONESCTABANC.CodCtaBancaria --CTASBANCARIAS.CodFondo = SOLRESC.CodFondo AND CTASBANCARIAS.CodMoneda = SOLRESC.CodMoneda
		LEFT JOIN TPCTABANCARIA TPCTAFDO ON CTASBANCARIAS.CodTpCtaBancaria = TPCTAFDO.CodTpCtaBancaria
		INNER JOIN MONEDAS on MONEDAS.CodMoneda = SOLRESC.CodMoneda
		INNER JOIN CPTCTASBANCARIAS ON  CPTCTASBANCARIAS.CodCuotapartista = SOLRESC.CodCuotapartista AND CPTCTASBANCARIAS.CodMoneda = SOLRESC.CodMoneda AND CPTCTASBANCARIAS.EstaAnulado = 0 
		INNER JOIN TPCTABANCARIA ON CPTCTASBANCARIAS.CodTpCtaBancaria = TPCTABANCARIA.CodTpCtaBancaria
		CROSS APPLY (SELECT TOP 1 * FROM CONDOMINIOS WHERE CodCuotapartista = SOLRESC.CodCuotapartista) CONDOMINIOS
		--INNER JOIN CONDOMINIOS ON CUOTAPARTISTAS.CodCuotapartista=CONDOMINIOS.CodCuotapartista 
		INNER JOIN PERSONAS ON PERSONAS.CodPersona=CONDOMINIOS.CodPersona
		LEFT JOIN LIQUIDACIONESIMPMON ON LIQUIDACIONESIMPMON.CodLiquidacion = LIQUIDACIONES.CodLiquidacion
		INNER JOIN FORMASPAGO ON FORMASPAGO.CodFormaPago = SOLRESC.CodFormaPago
	WHERE  SOLRESC.EstaAnulado = 0
	AND SOLRESC.CodTpEstadoSol NOT IN ('RECH', 'INC')
	AND LIQUIDACIONES.FechaLiquidacion IN ('20201016','20201022','20201103')
	AND LIQUIDACIONESIMPMON.CodLiquidacion IS NULL
	AND SOLRESCIMPMON.serviceProc = 0
	AND FORMASPAGO.CodTpFormaPago = 'CB' AND SOLRESC.CodTpOrigenSol <>'VF'


	UNION ALL

	
	SELECT 
		SOLRESC.CodSolResc CodSolResc,
		LIQUIDACIONES.CodLiquidacion CodLiquidacion,
		FONDOSPARAM.CodParametroFdo CodParametroFdo,
		(SELECT TOP 1 ValorCuotaparte FROM VALORESCP where CodFondo = SOLRESC.CodFondo and CodTpValorCp = SOLRESC.CodTpValorCp and Fecha <= '20201103' ORDER BY Fecha DESC) ValorCuotaparte,
		LIQUIDACIONES.CantCuotapartes CantCuotapartes,
		LIQUIDACIONES.Importe Importe,
		SOLRESCIMPMON.CodAgColocador CodAgColocador,
		SOLRESCIMPMON.CodSucursal CodSucursal,
		SOLRESCIMPMON.serviceProc serviceProc,
		ISNULL(SOLRESCIMPMON.ImporteDif,0) ImporteDif,
		LIQUIDACIONES.Importe ImporteLiq,
		(SELECT TOP 1 ValorCuotaparte FROM VALORESCP where CodFondo = SOLRESC.CodFondo and CodTpValorCp = SOLRESC.CodTpValorCp and Fecha <= '20201103' ORDER BY Fecha DESC) AS UltValorCuotaparte,
		SOLRESCIMPMON.CodTpEstadoImpMon CodTpEstadoImpMon,

		--DATOS IMPACTO
		CUOTAPARTISTAS.NumCuotapartista AS NumCuotapartista,
		CUOTAPARTISTAS.Nombre AS Nombre,
		FONDOSREAL.NumFondo AS NumFondo,
		FONDOSREAL.CodFondo AS CodFondo,
		TPVALORESCP.Abreviatura as Abreviatura,
		'0101' [CentroCostoSucursal], --CPTCTASBANCARIAS.NumSucursal AS CentroCostoSucursal,

		--ORIGEN - DEBITO - FONDO
		'0101' [CuentaBancariaSucursal],
		TPCTAFDO.CodInterfaz as CuentaBancariaTipo,
		CTASBANCARIAS.NumeroCuenta as CuentaBancariaNumero,
		MONEDAS.CodInterfaz AS CuentaBancariaMoneda,

		--DESTINO - CREDITO - CPT
		'0' + LTRIM(CPTCTASBANCARIAS.NumSucursal) AS CuentaFondoSucursal ,
		TPCTABANCARIA.CodInterfaz AS CuentaFondoTipo ,
		CPTCTASBANCARIAS.NumeroCuenta AS CuentaFondoNumero ,
		MONEDAS.CodInterfaz AS CuentaFondoMoneda,

		CASE WHEN PERSONAS.CUIL IS NULL AND PERSONAS.CUIT IS NULL THEN
				(SELECT TOP 1 CodInterfaz FROM TPDOCIDENTIDAD WHERE CodDocIdentidad = 'DNI')
			WHEN PERSONAS.CUIL IS NULL THEN
				(SELECT TOP 1 CodInterfaz FROM TPDOCIDENTIDAD WHERE CodDocIdentidad = 'CUIT')
			ELSE
				(SELECT TOP 1 CodInterfaz FROM TPDOCIDENTIDAD WHERE CodDocIdentidad = 'CUIL')
			END TpDocumento,
		CASE WHEN PERSONAS.CUIL IS NULL AND PERSONAS.CUIT IS NULL THEN
				PERSONAS.NumDocumento
			WHEN PERSONAS.CUIL IS NOT NULL THEN
				PERSONAS.CUIL
			ELSE
				PERSONAS.CUIT
			END NumDocumento
	FROM SOLRESC
		INNER JOIN LIQUIDACIONES ON LIQUIDACIONES.CodSolResc = SOLRESC.CodSolResc AND LIQUIDACIONES.EstaAnulado = 0
		INNER JOIN FONDOSPARAM ON FONDOSPARAM.CodFondo = SOLRESC.CodFondo AND CodParametroFdo = 'IMSOT0'
		INNER JOIN SOLRESCIMPMON ON SOLRESCIMPMON.CodFondo = SOLRESC.CodFondo AND SOLRESCIMPMON.CodSolResc = SOLRESC.CodSolResc --AND SOLRESCIMPMON.CodTpEstadoImpMon = 'IR'
		INNER JOIN CUOTAPARTISTAS ON SOLRESC.CodCuotapartista = CUOTAPARTISTAS.CodCuotapartista
		INNER JOIN FONDOSREAL ON FONDOSREAL.CodFondo = SOLRESC.CodFondo
		INNER JOIN TPVALORESCP ON TPVALORESCP.CodFondo = SOLRESC.CodFondo AND TPVALORESCP.CodTpValorCp = SOLRESC.CodTpValorCp
		INNER JOIN AFECTACIONESCTABANC ON AFECTACIONESCTABANC.CodFondo = SOLRESC.CodFondo AND AFECTACIONESCTABANC.CodMoneda = SOLRESC.CodMoneda AND CodTpAfectacionBanc = 'LIQRES'
		INNER JOIN CTASBANCARIAS ON CTASBANCARIAS.CodCtaBancaria = AFECTACIONESCTABANC.CodCtaBancaria --CTASBANCARIAS.CodFondo = SOLRESC.CodFondo AND CTASBANCARIAS.CodMoneda = SOLRESC.CodMoneda
		LEFT JOIN TPCTABANCARIA TPCTAFDO ON CTASBANCARIAS.CodTpCtaBancaria = TPCTAFDO.CodTpCtaBancaria
		INNER JOIN MONEDAS on MONEDAS.CodMoneda = SOLRESC.CodMoneda
		INNER JOIN CPTCTASBANCARIAS ON  CPTCTASBANCARIAS.CodCuotapartista = SOLRESC.CodCuotapartista AND CPTCTASBANCARIAS.CodMoneda = SOLRESC.CodMoneda AND CPTCTASBANCARIAS.EstaAnulado = 0 
		INNER JOIN TPCTABANCARIA ON CPTCTASBANCARIAS.CodTpCtaBancaria = TPCTABANCARIA.CodTpCtaBancaria
		CROSS APPLY (SELECT TOP 1 * FROM CONDOMINIOS WHERE CodCuotapartista = SOLRESC.CodCuotapartista) CONDOMINIOS
		--INNER JOIN CONDOMINIOS ON CUOTAPARTISTAS.CodCuotapartista=CONDOMINIOS.CodCuotapartista 
		INNER JOIN PERSONAS ON PERSONAS.CodPersona=CONDOMINIOS.CodPersona
		LEFT JOIN LIQUIDACIONESIMPMON ON LIQUIDACIONESIMPMON.CodLiquidacion = LIQUIDACIONES.CodLiquidacion
		INNER JOIN FORMASPAGO ON FORMASPAGO.CodFormaPago = SOLRESC.CodFormaPago
	WHERE  SOLRESC.EstaAnulado = 0
	AND SOLRESC.CodTpEstadoSol NOT IN ('RECH', 'INC')
	AND LIQUIDACIONES.FechaLiquidacion IN ('20201016','20201022','20201103')
	AND LIQUIDACIONESIMPMON.CodLiquidacion IS NULL
	AND SOLRESCIMPMON.serviceProc = 0
	AND FORMASPAGO.CodTpFormaPago = 'CB' AND SOLRESC.CodTpOrigenSol ='VF'