DECLARE @CodFondo numeric(10) 

SELECT @CodFondo=CodFondo FROM FONDOSREAL
WHERE NumFondo=13

DECLARE @CodCuotapartista numeric(10) 

SELECT @CodCuotapartista=CodCuotapartista FROM CUOTAPARTISTAS
WHERE NumCuotapartista=2009


SELECT FONDOS.*
FROM FONDOS
INNER JOIN FONDOSCPT ON FONDOS.CodFondo = FONDOSCPT.CodFondo
INNER JOIN CUOTAPARTISTAS ON CUOTAPARTISTAS.CodCuotapartista = FONDOSCPT.CodCuotapartista
WHERE FONDOS.CodFondo=@CodFondo and CUOTAPARTISTAS.CodCuotapartista = @CodCuotapartista


SELECT * FROM 
FONDOSREAL 
INNER JOIN FONDOSUSER ON FONDOSUSER.CodFondo = FONDOSREAL.CodFondo
INNER JOIN USUARIOSREL ON USUARIOSREL.CodFondoPorDefecto = FONDOSUSER.CodFondo AND USUARIOSREL.CodUsuario = FONDOSUSER.CodUsuario
INNER JOIN USUARIOS ON USUARIOS.CodUsuario = USUARIOSREL.CodUsuario AND UserIDExterno='H00031'
INNER JOIN TPVALORESCP ON TPVALORESCP.CodFondo = FONDOSREAL.CodFondo
WHERE FONDOSUSER.CodFondo=@CodFondo --and CUOTAPARTISTAS.CodCuotapartista = @CodCuotapartista



SELECT FONDOS.*
FROM FONDOS
INNER JOIN FONDOSCPT ON FONDOS.CodFondo = FONDOSCPT.CodFondo
INNER JOIN CUOTAPARTISTAS ON CUOTAPARTISTAS.CodCuotapartista = FONDOSCPT.CodCuotapartista
LEFT JOIN AGCOLOCFONDOS ON CUOTAPARTISTAS.CodAgColocador = AGCOLOCFONDOS.CodAgColocador
LEFT JOIN AGCOLOCFONDOS AGCOLOCFONDOS2 ON CUOTAPARTISTAS.CodAgColocadorOfCta = AGCOLOCFONDOS.CodAgColocador
WHERE FONDOS.CodFondo=@CodFondo and CUOTAPARTISTAS.CodCuotapartista = @CodCuotapartista


SELECT FONDOS.*
FROM FONDOS
INNER JOIN FONDOSCPT ON FONDOS.CodFondo = FONDOSCPT.CodFondo
INNER JOIN CUOTAPARTISTAS ON CUOTAPARTISTAS.CodCuotapartista = FONDOSCPT.CodCuotapartista
INNER JOIN SUCFONDOS ON CUOTAPARTISTAS.CodSucursal = SUCFONDOS.CodSucursal
WHERE FONDOS.CodFondo=@CodFondo and CUOTAPARTISTAS.CodCuotapartista = @CodCuotapartista