USE vfHome --SE DEBERÁ PONER EL NOMBRE DE LA BASE DE VFHOME
GO

UPDATE PARAMETROSENT
SET 
ValorFecha = NULL,
ValorTexto = NULL,
ValorNumerico = NULL
WHERE CodParametroEnt IN ('WSCRTK','WSCRTP','WSLOG')

GO

USE VFondos --SE DEBERÁ PONER EL NOMBRE DE LA BASE DE VFONDOS
GO

DELETE FROM AGCOLOCPARAM
WHERE CodAgColocador IN (8, 9) AND CodAgColocParam IN ('WSUSR','WSURL','WSTPRO','WSMONE','WSPASS','WSCHAN','WSABRV')

