SELECT * FROM CUOTAPARTISTAS
WHERE CodInterfaz = '400798'

SELECT * FROM AGCOLOCADORES
WHERE CodInterfaz = '2'

SELECT * FROM SUCURSALES
WHERE CodInterfaz = '1'

SELECT * FROM CANALESVTA
WHERE CodInterfaz = 'WEB'

SELECT * FROM CPTCTASBANCARIAS
WHERE CodInterfaz = '400798'

SELECT * FROM FORMASPAGO
WHERE CodInterfaz = '1'

