SELECT * FROM SUCURSALES
SELECT * FROM AGCOLOCADORES
SELECT * FROM CANALESVTA
SELECT * FROM FORMASPAGO
SELECT * FROM OFICIALESCTA
SELECT * FROM CUOTAPARTISTAS
SELECT * FROM CONDICIONESINGEGR
SELECT * FROM TPORIGENSOL
SELECT * FROM FONDOSREAL
SELECT * FROM TPVALORESCP


