SELECT CUOTAPARTISTAS.CodCuotapartista
,CUOTAPARTISTAS.NumCuotapartista
,CUOTAPARTISTAS.Nombre
,CUOTAPARTISTAS.Calle
,CUOTAPARTISTAS.AlturaCalle
,CUOTAPARTISTAS.Piso
,CUOTAPARTISTAS.Departamento
,CUOTAPARTISTAS.CodigoPostal
,CUOTAPARTISTAS.Localidad
,CUOTAPARTISTAS.Telefono
,CUOTAPARTISTAS.Fax
,CUOTAPARTISTAS.EMail
,CUOTAPARTISTAS.CodProvincia
,CUOTAPARTISTAS.CodPais


,PERSONAS.CodPersona, PERSONAS.Nombre, PERSONAS.Apellido, PERSONAS.NumDocumento, PERSONAS.CUIL, PERSONAS.CUIT 
,PERSONAS.Calle
,PERSONAS.AlturaCalle
,PERSONAS.Piso
,PERSONAS.Departamento
,PERSONAS.CodigoPostal
,PERSONAS.Localidad
,PERSONAS.Telefono
,PERSONAS.Fax
,PERSONAS.EMail
,PERSONAS.CodProvincia
,PERSONAS.CodPais


FROM CUOTAPARTISTAS
INNER JOIN CONDOMINIOS ON CUOTAPARTISTAS.CodCuotapartista = CONDOMINIOS.CodCuotapartista
INNER JOIN PERSONAS ON PERSONAS.CodPersona = CONDOMINIOS.CodPersona