DECLARE @CodFondo numeric(10)

SELECT @CodFondo=CodFondo
FROM FONDOSREAL
WHERE NumFondo='2203'


ALTER TABLE ASIENTOSIT  
NOCHECK CONSTRAINT CFK_ASIENTOSIT_ASIENTOSCAB_1;  
  

DELETE ASIENTOSIT
WHERE CodFondo=@CodFondo AND CodTpPlanCtaContable='ORIGIN' AND NumAsiento IN (SELECT NumAsiento FROM ASIENTOSCAB WHERE CodFondo=@CodFondo AND FechaConcertacion='20220113')

DELETE ASIENTOSCABREL
WHERE CodFondo=@CodFondo AND NumAsiento IN (SELECT NumAsiento FROM ASIENTOSCAB WHERE CodFondo=@CodFondo AND FechaConcertacion='20220113')


DELETE ASIENTOSCAB
WHERE CodFondo=@CodFondo AND FechaConcertacion='20220113'


ALTER TABLE ASIENTOSIT  
CHECK CONSTRAINT CFK_ASIENTOSIT_ASIENTOSCAB_1;  
  
