SELECT DISTINCT DOCUMENTACIONESWEB.Descripcion As DocumentacionWeb,
		   TPDOCUMENTACIONWEB.CodTpDocumentacionWEB,
		   TPDOCUMENTACIONWEB.Descripcion TpDocumentacionWeb,
		   FONDOSREAL.NumFondo,
		   FONDOSREAL.Nombre As Fondo,
		   FONDOSREAL.NombreAbreviado,
		   CPTDOCUMENTACIONWEB.Fecha As FechaAceptacion,
		   CASE WHEN CPTDOCUMENTACIONWEB.Fecha > DOCUMENTACIONESWEB.FechaVigencia THEN 'SI' ELSE 'NO' END As Acepto
	FROM DOCUMENTACIONESWEB
		 INNER JOIN TPDOCUMENTACIONWEB ON DOCUMENTACIONESWEB.CodTpDocumentacionWEB = TPDOCUMENTACIONWEB.CodTpDocumentacionWEB
		 INNER JOIN FONDOSREAL ON DOCUMENTACIONESWEB.CodFondo = FONDOSREAL.CodFondo
		 LEFT JOIN CPTDOCUMENTACIONWEB	ON CPTDOCUMENTACIONWEB.CodDocumentacionWEB = DOCUMENTACIONESWEB.CodDocumentacionWEB
	