CREATE TABLE #SALDOCUOTAPARTISTAS(CodCuotapartista numeric(10,0) NOT NULL , CodFondo numeric(5,0) NOT NULL , CodTpValorCp numeric(3,0) NOT NULL , NumFondo numeric(6,0) NULL , NumCuotapartista numeric(15,0) NULL , SaldoCuo numeric(22,8) NULL , SaldoCuoDis numeric(22,8) NULL , ValorCpt numeric(19,10) NULL , NombreFdo varchar(15) COLLATE database_default NULL , NomCortoFondo varchar(80) COLLATE database_default NULL , NomLargoFondo varchar(150) COLLATE database_default NULL , Nombre varchar(50) COLLATE database_default NULL , CodOficialCtaId varchar(30) COLLATE database_default NULL , NumPerfil varchar(80) COLLATE database_default NULL , NumSucursal numeric(15,0) NULL , CodInterfazFdoId varchar(30) COLLATE database_default NULL , CodInterfazReg varchar(30) COLLATE database_default NULL , CodCategoriaId varchar(30) COLLATE database_default NULL , CodReferenteId varchar(30) COLLATE database_default NULL , CodAgColocadorId varchar(30) COLLATE database_default NULL , CodSucursalId varchar(30) COLLATE database_default NULL , CodCanalVtaId varchar(30) COLLATE database_default NULL , CodSegmentoInvId varchar(30) COLLATE database_default NULL , Fecha smalldatetime NULL , NumCus varchar(30) COLLATE database_default NULL , SalVal numeric(19,2) NULL , FeVaCuot smalldatetime NULL , SaldoCuo2 numeric(22,8) NULL , TpValorCpId varchar(30) COLLATE database_default NULL , TpValorCpReexpID varchar(30) COLLATE database_default NULL , CodAgColocadorOrId varchar(30) COLLATE database_default NULL , CodSucursalOrId varchar(30) COLLATE database_default NULL , CCteCpt numeric(19,2) NULL , SaldoValorizado numeric(19,2) NULL , PrecioPromedio numeric(19,10) NULL , SaldoNoDisp numeric(22,8) NULL , CodInterfazMonFdo varchar(30) COLLATE database_default NULL , CodAuditoriaRefCpt numeric(10,0) NULL , CodFondoCNV varchar(30) COLLATE database_default NULL , CodCAFCIClaseCpt varchar(30) COLLATE database_default NULL , CodCAFCIMoneda varchar(30) COLLATE database_default NULL , FechaProceso smalldatetime NULL )

CREATE TABLE #CUOTAPARTISTASTEMP(CodCuotapartista numeric(10,0) NOT NULL , NumCuotapartista numeric(15,0) NULL , Nombre varchar(50) COLLATE database_default NULL , CodOficialCtaId varchar(30) COLLATE database_default NULL , CodInterfaz varchar(30) COLLATE database_default NULL , CodCategoriaId varchar(30) COLLATE database_default NULL , CodReferenteId varchar(30) COLLATE database_default NULL , CodAgColocadorId varchar(30) COLLATE database_default NULL , CodSucursalId varchar(30) COLLATE database_default NULL , CodCanalVtaId varchar(30) COLLATE database_default NULL , CodSegmentoInvId varchar(30) COLLATE database_default NULL , NumCus varchar(80) COLLATE database_default NULL , CodAgColocadorOrId varchar(30) COLLATE database_default NULL , CodSucursalOrId varchar(30) COLLATE database_default NULL , NumSucursal numeric(15,0) NULL , Perfil varchar(80) COLLATE database_default NULL )

CREATE TABLE #FONDOS(CodFondo numeric(10,0) NOT NULL , NRCNV numeric(15,0) NULL , CodAgColocadorDep numeric(10,0) NULL , CodInterfaz varchar(30) COLLATE database_default NULL )

exec spSPosicionCuotapartista_1 NULL,NULL,NULL,NULL,NULL,NULL,NULL,'SASCP',9,NULL,NULL,0,'2020-09-02 00:00:00'
exec spSPosicionCuotapartista_2 '2020-09-02 00:00:00',NULL,1,NULL,-1,0
exec spSPosicionCuotapartista_3 '2020-09-02 00:00:00'


SELECT 'SCP' As InterfazItId,NumFondo,NumCuotapartista ,SaldoCuo,SaldoCuoDis,ValorCpt,NombreFdo,Nombre,CodOficialCtaId,NumPerfil,NumSucursal,CodInterfazFdoId,CodInterfazReg,CodCategoriaId,CodReferenteId,CodAgColocadorId,CodSucursalId,CodCanalVtaId,CodSegmentoInvId,Fecha ,NumCus,SalVal, FeVaCuot, SaldoCuo2, TpValorCpId, TpValorCpReexpID, CodAgColocadorOrId, CodSucursalOrId, CCteCpt, SaldoValorizado, PrecioPromedio, SaldoNoDisp, CodInterfazMonFdo, NomLargoFondo, NomCortoFondo  FROM #SALDOCUOTAPARTISTAS ORDER BY NumCuotapartista ASC  ,NumFondo ASC 

SELECT ActCtrlTotal, IDInterfaz, PermiteConfigRegional, coalesce(SeparadorDecimal,'') as SeparadorDecimal  FROM INTERFACESFMT  WHERE CodInterfaz = 'SASCP'  AND CodInterfazFmt = 9

SELECT INTERFACESREGIT.InterfazItId,INTERFACESREGIT.CodTpDatoInterf, INTERFACESREGIT.Largo, INTERFACESREGIT.Formato, COALESCE((SELECT COALESCE(INTERFACESREGITPOS.Posicion, 0) FROM INTERFACESREGITPOS WHERE INTERFACESREGIT.CodInterfaz = INTERFACESREGITPOS.CodInterfaz AND INTERFACESREGITPOS.CodInterfazReg = INTERFACESREGIT.CodInterfazReg AND INTERFACESREGITPOS.CodInterfazRegIt = INTERFACESREGIT.CodInterfazRegIt AND INTERFACESREGITPOS.CodInterfazFmt = 9),999999) AS SeMuestra  FROM INTERFACESREGIT INNER JOIN INTERFACESREG ON INTERFACESREG.CodInterfaz = INTERFACESREGIT.CodInterfaz AND INTERFACESREG.CodInterfazReg = INTERFACESREGIT.CodInterfazReg  WHERE INTERFACESREG.CodInterfazReg = 'SCP' AND INTERFACESREG.CodInterfaz = 'SASCP' ORDER BY SeMuestra 

SELECT INTERFACESREGIT.InterfazItId, INTERFACESREGITPOS.Posicion, INTERFACESREGIT.CodTpDatoInterf, INTERFACESREGITPOS.EsCampoTotal  FROM INTERFACESREGIT INNER JOIN INTERFACESREG ON INTERFACESREG.CodInterfaz = INTERFACESREGIT.CodInterfaz AND INTERFACESREG.CodInterfazReg = INTERFACESREGIT.CodInterfazReg LEFT JOIN INTERFACESREGITPOS ON INTERFACESREGITPOS.CodInterfaz = INTERFACESREGIT.CodInterfaz AND INTERFACESREGIT.CodInterfazReg = INTERFACESREGITPOS.CodInterfazReg  AND INTERFACESREGITPOS.CodInterfazRegIt = INTERFACESREGIT.CodInterfazRegIt  AND INTERFACESREGITPOS.CodInterfazFmt = 9 WHERE INTERFACESREGITPOS.FechaD IS NULL AND INTERFACESREG.CodInterfazReg = 'SCP' AND INTERFACESREG.CodInterfaz = 'SASCP' AND not INTERFACESREGITPOS.Posicion IS NULL ORDER BY INTERFACESREGITPOS.Posicion 

IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#SALDOCUOTAPARTISTAS')) DROP TABLE tempdb..#SALDOCUOTAPARTISTAS
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#CUOTAPARTISTASTEMP')) DROP TABLE tempdb..#CUOTAPARTISTASTEMP
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id = object_id('tempdb..#FONDOS')) DROP TABLE tempdb..#FONDOS

