USE VFondos
GO

SELECT SOLSUSCLIQMON.* 
FROM SOLSUSCLIQMON
INNER JOIN SOLSUSC ON SOLSUSC.CodSolSusc = SOLSUSCLIQMON.CodSolSusc
WHERE NumSolicitud = 264208

SELECT UserIDExterno FROM USUARIOS
WHERE CodUsuario In (SELECT SOLSUSCLIQMON.CodUsuarioImpactoCtaCpt
FROM SOLSUSCLIQMON
INNER JOIN SOLSUSC ON SOLSUSC.CodSolSusc = SOLSUSCLIQMON.CodSolSusc
WHERE NumSolicitud = 264208
UNION ALL
SELECT SOLSUSCLIQMON.CodUsuarioImpactoCtaFdo
FROM SOLSUSCLIQMON
INNER JOIN SOLSUSC ON SOLSUSC.CodSolSusc = SOLSUSCLIQMON.CodSolSusc
WHERE NumSolicitud = 264208
)

USE VFNet
GO

SELECT * 
FROM USUARIOS
WHERE UserID IN ([copiar los user ID que retorna la segunda consulta])
