SELECT CUOTAPARTISTAS.NumCuotapartista, 
CUOTAPARTISTAS.Nombre, PERSONAS.Nombre, PERSONAS.Apellido, PERSONAS.CodInterfazBanco, PERSONAS.CodSistemaExtOrig, CUOTAPARTISTAS.CodSistemaExtOrig, CUOTAPARTISTAS.CodInterfazBanco
FROM CUOTAPARTISTAS
INNER JOIN CONDOMINIOS ON CUOTAPARTISTAS.CodCuotapartista = CONDOMINIOS.CodCuotapartista
INNER JOIN PERSONAS ON PERSONAS.CodPersona = CONDOMINIOS.CodPersona
WHERE NumCuotapartista IN
(96540)