SELECT FONDOSREAL.NumFondo, FONDOSREAL.NombreCorto, TPVALORESCP.Abreviatura , CONDICIONESINGEGR.Descripcion, CONDICIONESINGEGR.SuscripcionMinima, CONDICIONESINGEGR.SuscripcionMaxima,  CONDINGEGRTPVALORESCP.EsDefault 
,CONDICIONESINGEGR.*
FROM CONDICIONESINGEGR 
INNER JOIN FONDOSREAL ON CONDICIONESINGEGR.CodFondo =FONDOSREAL.CodFondo
INNER JOIN TPVALORESCP ON TPVALORESCP.CodFondo = FONDOSREAL.CodFondo
INNER JOIN CONDINGEGRTPVALORESCP ON CONDICIONESINGEGR.CodCondicionIngEgr = CONDINGEGRTPVALORESCP.CodCondicionIngEgr AND CONDICIONESINGEGR.CodFondo = CONDINGEGRTPVALORESCP.CodFondo
AND TPVALORESCP.CodTpValorCp = CONDINGEGRTPVALORESCP.CodTpValorCp AND CONDINGEGRTPVALORESCP.EstaAnulado=0
WHERE FONDOSREAL.EstaAnulado=0 AND CONDICIONESINGEGR.EstaAnulado=0


SELECT CodCuotapartista, CodFondo, CodTpValorCp, SUM(CantCuotapartes)
FROM LIQUIDACIONES
WHERE CodFondo=1-- AND CodTpValorCp=@CodTpValorCp
GROUP BY CodCuotapartista, CodFondo, CodTpValorCp
HAVING SUM(CantCuotapartes) >0
ORDER BY CodCuotapartista, CodFondo


24	5	12	616507826.11391388
24	5	5	14804818.00000000

SELECT * FROM SOLSUSC
WHERE  CodCuotapartista IN (407,8842)
AND FechaConcertacion='20200819'

SELECT CUOTAPARTISTAS.CodCuotapartista, NumCuotapartista ,NumeroCuenta FROM CUOTAPARTISTAS
INNER JOIN CPTCTASBANCARIAS ON CPTCTASBANCARIAS.CodCuotapartista=CUOTAPARTISTAS.CodCuotapartista
WHERE CUOTAPARTISTAS.CodCuotapartista IN (407,8842)
--407	1	9
--8842	1	1