--SELECT FONDOSMEGA.CodFondo, FONDOSQM.Nombre
--FROM VFondos.dbo.FONDOSREAL FONDOSQM
--INNER JOIN VFondos_2.dbo.FONDOSREAL FONDOSMEGA ON FONDOSQM.Nombre = FONDOSMEGA.Nombre


begin TRAN

INSERT INTO VFondos_2.dbo.AUDITORIASREF
SELECT 'REGLGESTION'

DECLARE @CodAuditoriaRef numeric(30)
SET @CodAuditoriaRef = @@IDENTITY

--INSERT INTO VFondos_2.dbo.REGLGESTION(CodFondo,NombreArchivo,Descripcion,FechaInicioVigencia,EstaAnulado,CodAuditoriaRef)
SELECT FONDOSMEGA.CodFondo,REGLGESTIONQM.NombreArchivo,REGLGESTIONQM.Descripcion,REGLGESTIONQM.FechaInicioVigencia, 0, 1
FROM VFondos.dbo.REGLGESTION REGLGESTIONQM
INNER JOIN VFondos.dbo.FONDOSREAL FONDOSQM ON REGLGESTIONQM.CodFondo = FONDOSQM.CodFondo
INNER JOIN VFondos_2.dbo.FONDOSREAL FONDOSMEGA ON FONDOSQM.Nombre = FONDOSMEGA.Nombre
WHERE REGLGESTIONQM.EstaAnulado=0

INSERT INTO VFondos_2.dbo.REGLGESTIONDATOS
SELECT REGLGESTIONMEGA.CodReglGestion, REGLGESTIONMEGA.CodFondo, REGLGESTIONDATOSQM.Datos
FROM VFondos.dbo.REGLGESTION REGLGESTIONQM
INNER JOIN VFondos.dbo.FONDOSREAL FONDOSQM ON REGLGESTIONQM.CodFondo = FONDOSQM.CodFondo
INNER JOIN VFondos.dbo.REGLGESTIONDATOS REGLGESTIONDATOSQM ON REGLGESTIONDATOSQM.CodFondo = REGLGESTIONQM.CodFondo AND REGLGESTIONDATOSQM.CodReglGestion = REGLGESTIONQM.CodReglGestion
INNER JOIN VFondos_2.dbo.FONDOSREAL FONDOSMEGA ON FONDOSQM.Nombre = FONDOSMEGA.Nombre
INNER JOIN VFondos_2.dbo.REGLGESTION REGLGESTIONMEGA ON REGLGESTIONMEGA.Descripcion = REGLGESTIONQM.Descripcion and REGLGESTIONMEGA.FechaInicioVigencia = REGLGESTIONQM.FechaInicioVigencia
WHERE REGLGESTIONQM.EstaAnulado=0 --AND REGLGESTIONMEGA.FechaInicioVigencia IN (SELECT MAX(FechaInicioVigencia) FROM VFondos_2.dbo.REGLGESTION WHERE REGLGESTIONMEGA.CodFondo=REGLGESTION.CodFondo AND REGLGESTION.CodReglGestion = REGLGESTIONMEGA.CodReglGestion AND REGLGESTION.FechaInicioVigencia < GETDATE() )

