--SELECT FONDOSMEGA.Nombre, NumSolicitud, Importe 
--FROM VFondos_2.dbo.SOLSUSC
--INNER JOIN VFondos_2.dbo.FONDOSREAL FONDOSMEGA ON SOLSUSC.CodFondo = FONDOSMEGA.CodFondo
--INNER JOIN VFondos.dbo.FONDOSREAL FONDOSQM ON FONDOSQM.Nombre = FONDOSMEGA.Nombre

--WHERE FechaConcertacion between '20220214' and '20220218'


SELECT FONDOSMEGA.Nombre, CLASESQM.Abreviatura, CPTQM.Nombre, SOLRESCMEGA.NumSolicitud as NumSolicitudMega, SOLRESCQM.NumSolicitud as NumSolicitudQM, SOLRESCMEGA.FechaConcertacion, SOLRESCMEGA.Importe, SOLRESCMEGA.CantCuotapartes , 'RESCATE'
FROM VFondos_2.dbo.SOLRESC SOLRESCMEGA
INNER JOIN VFondos_2.dbo.FONDOSREAL FONDOSMEGA ON SOLRESCMEGA.CodFondo = FONDOSMEGA.CodFondo
INNER JOIN VFondos.dbo.FONDOSREAL FONDOSQM ON FONDOSQM.Nombre = FONDOSMEGA.Nombre

INNER JOIN VFondos_2.dbo.MONEDAS MONEDASMEGA ON SOLRESCMEGA.CodMoneda = MONEDASMEGA.CodMoneda
INNER JOIN VFondos.dbo.MONEDAS MONEDASQM ON MONEDASMEGA.Simbolo = MONEDASQM.Simbolo

INNER JOIN VFondos_2.dbo.TPVALORESCP CLASESMEGA ON SOLRESCMEGA.CodFondo = CLASESMEGA.CodFondo AND SOLRESCMEGA.CodTpValorCp = CLASESMEGA.CodTpValorCp
INNER JOIN VFondos.dbo.TPVALORESCP CLASESQM ON FONDOSQM.CodFondo = CLASESQM.CodFondo AND CLASESQM.Abreviatura = CLASESMEGA.Abreviatura

INNER JOIN VFondos_2.dbo.CONDICIONESINGEGR CONDMEGA ON SOLRESCMEGA.CodFondo = CONDMEGA.CodFondo AND SOLRESCMEGA.CodCondicionIngEgr = CONDMEGA.CodCondicionIngEgr
INNER JOIN VFondos.dbo.CONDICIONESINGEGR CONDQM ON CONDQM.Descripcion = CONDMEGA.Descripcion AND CONDQM.CodFondo = FONDOSQM.CodFondo

INNER JOIN VFondos_2.dbo.CUOTAPARTISTAS CPTMEGA ON CPTMEGA.CodCuotapartista=SOLRESCMEGA.CodCuotapartista
INNER JOIN VFondos.dbo.CUOTAPARTISTAS CPTQM ON CPTMEGA.NumCuotapartista = '100' + LTRIM(CPTQM.NumCuotapartista)

LEFT JOIN VFondos.dbo.SOLRESC SOLRESCQM ON SOLRESCQM.CodFondo = CLASESQM.CodFondo AND SOLRESCQM.CodTpValorCp = CLASESQM.CodTpValorCp
 AND SOLRESCQM.CodCondicionIngEgr = CONDQM.CodCondicionIngEgr AND SOLRESCQM.CodCuotapartista = CPTQM.CodCuotapartista
 AND ISNULL(SOLRESCQM.Importe,0)  = ISNULL(SOLRESCMEGA.Importe,0) AND ISNULL(SOLRESCQM.CantCuotapartes,0) = ISNULL(SOLRESCMEGA.CantCuotapartes, 0) AND SOLRESCQM.FechaConcertacion=SOLRESCMEGA.FechaConcertacion
 AND SOLRESCQM.FechaAcreditacion=SOLRESCMEGA.FechaAcreditacion

WHERE SOLRESCMEGA.CodFondo >=134 AND SOLRESCMEGA.FechaConcertacion between '20220214' and '20220218'
AND SOLRESCMEGA.EstaAnulado=0
ORDER BY SOLRESCMEGA.FechaConcertacion ASC
--SELECT *
--FROM VFondos_2.dbo.SOLRESC
--WHERE SOLRESC.CodFondo >=134 AND FechaConcertacion between '20220214' and '20220225'
--AND SOLRESC.EstaAnulado=0
