
exec sp_CreateProcedure 'dbo.spRptLiquidacionesRescate'
GO

ALTER PROCEDURE dbo.spRptLiquidacionesRescate	
	@FechaLiquidacion Fecha
WITH ENCRYPTION
AS
	SELECT
		FONDOSREAL.Nombre [Fondo Descripción], 
		TPVALORESCP.Descripcion [Tipo VCP], 
		LIQUIDACIONES.FechaLiquidacion [Acreditación],
		CUOTAPARTISTAS.NumCuotapartista [Cpt Número],
		CUOTAPARTISTAS.Nombre [Cpt Nombre],
		TPESTADOSOL.Descripcion [Estado de Autorización],
		CPTCTASBANCARIAS.CBU CBU,
		LIQUIDACIONES.Importe [Monto],
		SOLRESC.NumSolicitud [Número],
		SOLRESCSONIC.IdCredito [Crédito OK]
	FROM LIQUIDACIONES
	INNER JOIN FONDOSREAL ON FONDOSREAL.CodFondo = LIQUIDACIONES.CodFondo
	INNER JOIN TPVALORESCP ON  TPVALORESCP.CodFondo = LIQUIDACIONES.CodFondo 
		AND TPVALORESCP.CodTpValorCp = LIQUIDACIONES.CodTpValorCp
	INNER JOIN CUOTAPARTISTAS ON CUOTAPARTISTAS.CodCuotapartista = LIQUIDACIONES.CodCuotapartista
	INNER JOIN SOLRESC ON SOLRESC.CodSolResc = LIQUIDACIONES.CodSolResc
		AND LIQUIDACIONES.CodFondo = SOLRESC.CodFondo
		AND LIQUIDACIONES.CodAgColocador = SOLRESC.CodAgColocador
		AND LIQUIDACIONES.CodSucursal = SOLRESC.CodSucursal
		AND LIQUIDACIONES.EstaAnulado  = 0  
	INNER JOIN TPESTADOSOL ON TPESTADOSOL.CodTpEstadoSol = SOLRESC.CodTpEstadoSol
	INNER JOIN CPTCTASBANCARIAS ON CPTCTASBANCARIAS.CodCuotapartista = LIQUIDACIONES.CodCuotapartista
		AND CPTCTASBANCARIAS.CodCtaBancaria = SOLRESC.CodCtaBancaria
	--INNER JOIN CONDOMINIOS ON CONDOMINIOS.CodCuotapartista = LIQUIDACIONES.CodCuotapartista
	--INNER JOIN PERSONAS ON PERSONAS.CodPersona = CONDOMINIOS.CodPersona
	LEFT JOIN SOLRESCSONIC ON SOLRESCSONIC.CodSolResc = LIQUIDACIONES.CodSolResc
		AND SOLRESCSONIC.CodFondo = SOLRESC.CodFondo
		AND SOLRESCSONIC.CodAgColocador = SOLRESC.CodAgColocador
		AND SOLRESCSONIC.CodSucursal = SOLRESC.CodSucursal
	WHERE (@FechaLiquidacion IS NULL OR LIQUIDACIONES.FechaLiquidacion = @FechaLiquidacion) 
	ORDER BY 1

	SELECT 
		FONDOSREAL.Nombre [Fondo],
		MONEDAS.Simbolo [Moneda],
		SUM(LIQUIDACIONES.Importe) [Monto],
		MONEDAS.CodCAFCI [CodMoneda]
	FROM LIQUIDACIONES
	INNER JOIN FONDOSREAL ON FONDOSREAL.CodFondo = LIQUIDACIONES.CodFondo
	INNER JOIN SOLRESC ON SOLRESC.CodSolResc = LIQUIDACIONES.CodSolResc
		AND LIQUIDACIONES.CodFondo = SOLRESC.CodFondo
		AND LIQUIDACIONES.CodAgColocador = SOLRESC.CodAgColocador
		AND LIQUIDACIONES.CodSucursal = SOLRESC.CodSucursal
		AND LIQUIDACIONES.EstaAnulado  = 0  
	INNER JOIN MONEDAS ON MONEDAS.CodMoneda = LIQUIDACIONES.CodMoneda
	INNER JOIN CPTCTASBANCARIAS ON CPTCTASBANCARIAS.CodCuotapartista = LIQUIDACIONES.CodCuotapartista
		AND CPTCTASBANCARIAS.CodCtaBancaria = SOLRESC.CodCtaBancaria
	WHERE -----MONEDAS.CodCAFCI IN ('ARS', 'USD') AND
	 (@FechaLiquidacion IS NULL OR LIQUIDACIONES.FechaLiquidacion = @FechaLiquidacion) 
	GROUP BY FONDOSREAL.Nombre, MONEDAS.Simbolo, MONEDAS.CodCAFCI
	ORDER BY FONDOSREAL.Nombre, MONEDAS.Simbolo, MONEDAS.CodCAFCI

	SELECT 
		TPCTABANCARIA.CodTpCtaBancariaSist [Tipo],
		TPCTABANCARIA.Descripcion [Descripcion], 
		MONEDAS.[Simbolo],
		SUM(LIQUIDACIONES.Importe) [Monto],
		MONEDAS.CodCAFCI [CodMoneda]
	FROM LIQUIDACIONES
	INNER JOIN MONEDAS ON MONEDAS.CodMoneda = LIQUIDACIONES.CodMoneda
	INNER JOIN SOLRESC ON SOLRESC.CodSolResc = LIQUIDACIONES.CodSolResc
		AND LIQUIDACIONES.CodFondo = SOLRESC.CodFondo
		AND LIQUIDACIONES.EstaAnulado  = 0  
		AND LIQUIDACIONES.CodAgColocador = SOLRESC.CodAgColocador
		AND LIQUIDACIONES.CodSucursal = SOLRESC.CodSucursal
	INNER JOIN CPTCTASBANCARIAS ON CPTCTASBANCARIAS.CodCtaBancaria = SOLRESC.CodCtaBancaria
		AND CPTCTASBANCARIAS.CodCuotapartista = SOLRESC.CodCuotapartista 
	INNER JOIN TPCTABANCARIA ON TPCTABANCARIA.CodTpCtaBancaria = CPTCTASBANCARIAS.CodTpCtaBancaria
	WHERE ----MONEDAS.CodCAFCI IN ('ARS', 'USD') AND 
	(@FechaLiquidacion IS NULL OR LIQUIDACIONES.FechaLiquidacion = @FechaLiquidacion) 
	GROUP BY TPCTABANCARIA.CodTpCtaBancariaSist, TPCTABANCARIA.Descripcion, MONEDAS.Simbolo, MONEDAS.CodCAFCI

	SELECT 
		MONEDAS.CodCAFCI [CodMoneda]
		,TPCTABANCARIA.Descripcion [Descripcion] 
		,MONEDAS.Simbolo [Moneda]
		,SUM(LIQUIDACIONES.Importe) [Monto]
	FROM LIQUIDACIONES
	INNER JOIN MONEDAS ON MONEDAS.CodMoneda = LIQUIDACIONES.CodMoneda
	INNER JOIN SOLRESC ON SOLRESC.CodSolResc = LIQUIDACIONES.CodSolResc
		AND LIQUIDACIONES.CodFondo = SOLRESC.CodFondo
		AND LIQUIDACIONES.CodAgColocador = SOLRESC.CodAgColocador
		AND LIQUIDACIONES.CodSucursal = SOLRESC.CodSucursal
		AND LIQUIDACIONES.EstaAnulado  = 0  
	INNER JOIN CPTCTASBANCARIAS ON CPTCTASBANCARIAS.CodCtaBancaria = SOLRESC.CodCtaBancaria
		AND CPTCTASBANCARIAS.CodCuotapartista = SOLRESC.CodCuotapartista 
	INNER JOIN TPCTABANCARIA ON TPCTABANCARIA.CodTpCtaBancaria = CPTCTASBANCARIAS.CodTpCtaBancaria
	WHERE -----MONEDAS.CodCAFCI IN ('ARS', 'USD') 
	----AND TPCTABANCARIA.CodInterfazBanco IN ('CTE', 'AHO') AND 
	(@FechaLiquidacion IS NULL OR LIQUIDACIONES.FechaLiquidacion = @FechaLiquidacion)
	GROUP BY MONEDAS.CodCAFCI, TPCTABANCARIA.Descripcion, MONEDAS.Simbolo
GO


exec sp_CreateProcedure 'dbo.spRptLiquidacionesSuscripcion'
GO

ALTER PROCEDURE dbo.spRptLiquidacionesSuscripcion	
	@FechaLiquidacion Fecha
WITH ENCRYPTION
AS
	SELECT
		--LIQUIDACIONES.CodLiquidacion,
		FONDOSREAL.Nombre [Fondo Descripción],
		SOLSUSC.NumSolicitud [Número],
		LIQUIDACIONES.FechaLiquidacion [Acreditación],
		CUOTAPARTISTAS.NumCuotapartista [Cpt Número],
		CUOTAPARTISTAS.Nombre [Cpt Nombre],
		--dbo.fnCUOTAPARTISTAS_GetCUIT(LIQUIDACIONES.CodCuotapartista),
		TPESTADOSOL.Descripcion [Estado de Autorización],
		CPTCTASBANCARIAS.CBU CBU,
		LIQUIDACIONES.Importe [Monto],
		--TPVALORESCP.Descripcion, 
		SOLSUSCSONIC.IdDebito [Débito OK]
		from
	LIQUIDACIONES
	INNER JOIN FONDOSREAL ON FONDOSREAL.CodFondo = LIQUIDACIONES.CodFondo
--	INNER JOIN TPVALORESCP ON  TPVALORESCP.CodFondo = LIQUIDACIONES.CodFondo AND TPVALORESCP.CodTpValorCp = LIQUIDACIONES.CodTpValorCp
	INNER JOIN CUOTAPARTISTAS ON CUOTAPARTISTAS.CodCuotapartista = LIQUIDACIONES.CodCuotapartista
	INNER JOIN SOLSUSC ON SOLSUSC.CodSolSusc = LIQUIDACIONES.CodSolSusc
		AND LIQUIDACIONES.CodFondo = SOLSUSC.CodFondo
		AND LIQUIDACIONES.CodAgColocador = SOLSUSC.CodAgColocador
		AND LIQUIDACIONES.CodSucursal = SOLSUSC.CodSucursal
		AND LIQUIDACIONES.EstaAnulado  = 0  
	INNER JOIN TPESTADOSOL ON TPESTADOSOL.CodTpEstadoSol = SOLSUSC.CodTpEstadoSol --Liquidada
	INNER JOIN SOLITCTASBANCARIAS ON SOLSUSC.CodCuotapartista = SOLITCTASBANCARIAS.CodCuotapartista
		AND SOLSUSC.CodSolSusc = SOLITCTASBANCARIAS.CodSolSusc
		AND SOLSUSC.CodFondo = SOLITCTASBANCARIAS.CodFondo
		AND SOLSUSC.CodAgColocador = SOLITCTASBANCARIAS.CodAgColocador
		AND SOLSUSC.CodSucursal = SOLITCTASBANCARIAS.CodSucursal
	INNER JOIN CPTCTASBANCARIAS ON CPTCTASBANCARIAS.CodCuotapartista = SOLITCTASBANCARIAS.CodCuotapartista
		AND CPTCTASBANCARIAS.CodCtaBancaria = SOLITCTASBANCARIAS.CodCtaBancaria
	--INNER JOIN CONDOMINIOS ON CONDOMINIOS.CodCuotapartista = LIQUIDACIONES.CodCuotapartista
	--INNER JOIN PERSONAS ON PERSONAS.CodPersona = CONDOMINIOS.CodPersona
	LEFT JOIN SOLSUSCSONIC ON SOLSUSCSONIC.CodSolSusc = SOLSUSC.CodSolSusc 
		AND SOLSUSCSONIC.CodFondo = SOLSUSC.CodFondo
		AND SOLSUSCSONIC.CodAgColocador = SOLSUSC.CodAgColocador
		AND SOLSUSCSONIC.CodSucursal = SOLSUSC.CodSucursal
	WHERE (@FechaLiquidacion IS NULL OR LIQUIDACIONES.FechaLiquidacion = @FechaLiquidacion) 
	ORDER BY 1
	--- Subtotales por Fondo
	SELECT 
		FONDOSREAL.Nombre [Fondo],
		MONEDAS.Simbolo [Moneda],
		SUM(LIQUIDACIONES.Importe) [Monto],
		CTASBANCARIAS.CBU [CBU],
		MONEDAS.CodCAFCI [CodMoneda]
	FROM LIQUIDACIONES
	INNER JOIN FONDOSREAL ON FONDOSREAL.CodFondo = LIQUIDACIONES.CodFondo
	INNER JOIN SOLSUSC ON SOLSUSC.CodSolSusc  = LIQUIDACIONES.CodSolSusc
		AND LIQUIDACIONES.CodFondo = SOLSUSC.CodFondo
		AND LIQUIDACIONES.CodAgColocador = SOLSUSC.CodAgColocador
		AND LIQUIDACIONES.CodSucursal = SOLSUSC.CodSucursal
		AND LIQUIDACIONES.EstaAnulado  = 0  
	INNER JOIN SOLITCTASBANCARIAS ON SOLSUSC.CodCuotapartista = SOLITCTASBANCARIAS.CodCuotapartista
		AND SOLSUSC.CodSolSusc = SOLITCTASBANCARIAS.CodSolSusc
		AND SOLSUSC.CodFondo = SOLITCTASBANCARIAS.CodFondo
		AND SOLSUSC.CodAgColocador = SOLITCTASBANCARIAS.CodAgColocador
		AND SOLSUSC.CodSucursal = SOLITCTASBANCARIAS.CodSucursal
	INNER JOIN CPTCTASBANCARIAS ON CPTCTASBANCARIAS.CodCuotapartista = SOLITCTASBANCARIAS.CodCuotapartista
		AND CPTCTASBANCARIAS.CodCtaBancaria = SOLITCTASBANCARIAS.CodCtaBancaria
	LEFT JOIN CTASBANCARIAS ON CTASBANCARIAS.CodFondo = LIQUIDACIONES.CodFondo
		AND CTASBANCARIAS.CodCtaBancaria = SOLITCTASBANCARIAS.CodCtaBancaria
	INNER JOIN MONEDAS ON MONEDAS.CodMoneda = LIQUIDACIONES.CodMoneda
	WHERE --MONEDAS.CodCAFCI IN ('ARS', 'USD') AND 
	(@FechaLiquidacion IS NULL OR LIQUIDACIONES.FechaLiquidacion = @FechaLiquidacion)
	GROUP BY FONDOSREAL.Nombre, MONEDAS.Simbolo, CTASBANCARIAS.CBU, MONEDAS.CodCAFCI
	ORDER BY FONDOSREAL.Nombre, MONEDAS.Simbolo, CTASBANCARIAS.CBU, MONEDAS.CodCAFCI

	-- Subtotales por Moneda
	SELECT
		MONEDAS.CodCAFCI [CodMoneda]
		--,TPCTABANCARIA.CodTpCtaBancaria [TPCuenta]
		,TPCTABANCARIA.Descripcion [Descripcion] 
		,MONEDAS.Simbolo [Moneda]
		,SUM(LIQUIDACIONES.Importe) [Monto]
	FROM LIQUIDACIONES
	INNER JOIN SOLSUSC ON SOLSUSC.CodSolSusc  = LIQUIDACIONES.CodSolSusc
		AND LIQUIDACIONES.CodFondo = SOLSUSC.CodFondo
		AND LIQUIDACIONES.CodAgColocador = SOLSUSC.CodAgColocador
		AND LIQUIDACIONES.CodSucursal = SOLSUSC.CodSucursal
		AND LIQUIDACIONES.EstaAnulado  = 0  
	INNER JOIN SOLITCTASBANCARIAS ON SOLSUSC.CodCuotapartista = SOLITCTASBANCARIAS.CodCuotapartista
		AND SOLSUSC.CodSolSusc = SOLITCTASBANCARIAS.CodSolSusc
		AND SOLSUSC.CodFondo = SOLITCTASBANCARIAS.CodFondo
		AND SOLSUSC.CodAgColocador = SOLITCTASBANCARIAS.CodAgColocador
		AND SOLSUSC.CodSucursal = SOLITCTASBANCARIAS.CodSucursal
	INNER JOIN CPTCTASBANCARIAS ON CPTCTASBANCARIAS.CodCuotapartista = SOLITCTASBANCARIAS.CodCuotapartista
		AND CPTCTASBANCARIAS.CodCtaBancaria = SOLITCTASBANCARIAS.CodCtaBancaria
	INNER JOIN TPCTABANCARIA ON TPCTABANCARIA.CodTpCtaBancaria = CPTCTASBANCARIAS.CodTpCtaBancaria
	INNER JOIN MONEDAS ON MONEDAS.CodMoneda = LIQUIDACIONES.CodMoneda
	---WHERE MONEDAS.CodCAFCI IN ('ARS', 'USD') 
	----AND TPCTABANCARIA.CodInterfazBanco IN ('CTE', 'AHO') 
	AND (@FechaLiquidacion IS NULL OR LIQUIDACIONES.FechaLiquidacion = @FechaLiquidacion)
	GROUP BY MONEDAS.CodCAFCI, TPCTABANCARIA.Descripcion, MONEDAS.Simbolo
GO