DECLARE @CodEntidad int
SET @CodEntidad = 134

DELETE FROM appENTFILTROSUSER WHERE CodEntidad = @CodEntidad
DELETE FROM appENTFILTROS WHERE CodEntidad = @CodEntidad
DELETE FROM appENTCOLUMNASUSER WHERE CodEntidad = @CodEntidad
DELETE FROM appENTCORTESUSER WHERE CodEntidad = @CodEntidad
DELETE FROM appENTCONFIGURACIONUSER WHERE CodEntidad = @CodEntidad
DELETE FROM appENTCOLUMNAS WHERE CodEntidad = @CodEntidad
--DELETE FROM appENTESTRUCTURAS WHERE CodEntidad = @CodEntidad

DELETE FROM appENTFILTROSSETUSER WHERE CodEntidad = @CodEntidad
DELETE FROM appENTTPACCION WHERE CodEntidad = @CodEntidad
DELETE FROM AUDITORIASHISTPERM WHERE CodEntidad = @CodEntidad
DELETE FROM appREQUESTHISTUSER WHERE CodEntidad = @CodEntidad
DELETE FROM appENTIDADES WHERE CodEntidad = @CodEntidad
--DELETE FROM appENTIDADESUSERFAV WHERE CodEntidad = @CodEntidad
