
 IF NOT EXISTS(SELECT * FROM sys.columns WHERE name IN ('CodSistema', 'Version') AND object_id=OBJECT_ID('DESCARGAS'))
 BEGIN

	ALTER TABLE DESCARGAS
	ADD CodSistema CodigoMedio NULL

	ALTER TABLE DESCARGAS
	ADD [Version] DescripcionMedia NULL


	IF not exists (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[CFK_DESCARGAS_SISTEMA]'))
	begin
		ALTER TABLE DESCARGAS ADD CONSTRAINT CFK_DESCARGAS_SISTEMA FOREIGN KEY (CodSistema) REFERENCES SISTEMAS(CodSistema)
	end


 END

 IF NOT EXISTS(SELECT * FROM sys.objects WHERE name='USERDESCARGA')
 BEGIN

	CREATE TABLE dbo.USERDESCARGA(
		 CodUserDescarga	CodigoLargo NOT NULL IDENTITY(1,1),
		 CodUsuario			CodigoLargo	NOT NULL,
		 CodDescarga		CodigoLargo	NOT NULL,
		 EstaAnulado		Boolean		NOT NULL

	 CONSTRAINT XPKUSERDESCARGA PRIMARY KEY CLUSTERED 
		(
			CodUserDescarga ASC
		)
	)

	ALTER TABLE USERDESCARGA ADD CONSTRAINT CFK_USERDESCARGA_DESCARGA FOREIGN KEY (CodDescarga) REFERENCES DESCARGAS(CodDescarga)
	ALTER TABLE USERDESCARGA ADD CONSTRAINT CFK_USERDESCARGA_USUARIO FOREIGN KEY (CodUsuario) REFERENCES USUARIOS(CodUsuario)


 END

 
 IF NOT EXISTS(SELECT * FROM sys.objects WHERE name='USERSISTEMA')
 BEGIN

	CREATE TABLE dbo.USERSISTEMA(
		 CodUserSistema		CodigoLargo NOT NULL IDENTITY(1,1),
		 CodUsuario			CodigoLargo	NOT NULL,
		 CodSistema			CodigoMedio NOT NULL

	 CONSTRAINT XPKUSERSISTEMA PRIMARY KEY CLUSTERED 
		(
			CodUserSistema ASC
		)
	)

	ALTER TABLE USERSISTEMA ADD CONSTRAINT CFK_USERSISTEMA_SISTEMA FOREIGN KEY (CodSistema) REFERENCES SISTEMAS(CodSistema)
	ALTER TABLE USERSISTEMA ADD CONSTRAINT CFK_USERSISTEMA_USUARIO FOREIGN KEY (CodUsuario) REFERENCES USUARIOS(CodUsuario)

 END